name: flutter_map_dragmarker
description: Dragmarker class for flutter_map
version: 4.0.0-beta.1
repository: https://github.com/ibrierley/flutter_map_dragmarker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0-beta.1
  latlong2: ">=0.8.0 <0.9.0"

dev_dependencies:
  flutter_lints: ">=1.0.4"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
