name: flutter_map_dragmarker
description: Dragmarker class for flutter_map
version: 6.1.0
repository: https://github.com/ibrierley/flutter_map_dragmarker

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dependency_overrides:
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      # ref: main (custom branch/commit)

dev_dependencies:
  flutter_lints: ">=1.0.4"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
